### ISSUE TITLE
jwtRefreshExpiration

### ISSUE THREAD

**Issue by roestigraben** [mohammadali0120/nuxt-express-postgres-authentication#2]
jwtRefreshExpiration config seems not to have any effect.

I had it change from default 86400 (1 day) to 1 (1 sec), on my local storage of the app I always get a expiration date which is 1 month ahead in the future.

**Comment by mohammadali0120** [comment]
I also test this and I change it from 86400 to 20 seconds and the problem as you say was there, but I also decrease `jwtExpiration` to 10 seconds and after that, it's working
please mind to `jwtExpiration` it's equal one hour
and actually when you set `jwtRefreshExpiration` to 1 second its work as expected in your database (please check the `expiryDate` column in your database) 
but I don't know why expire date is still 1 month at the frontend, but trust me it will be working as you set in your backend because I've tested it now, and when I wrote it.

**Note:** do not store your token in localStorage is not safe, cookies would be enough 
if you don't know how:

```js
auth: {
 localStorage: false
 // ...
}

```

**Comment by roestigraben** [comment]
OK I test it right away! Thx
